import fs from 'node:fs';
import {makePath,parameterize,at,resample,makeCats} from '../track-review/geometry.mjs';
const root='art/concepts/v2_ui';
const catalog=JSON.parse(fs.readFileSync('design/track-review/catalog.source.json','utf8'));
for(const dir of ['prompts','blueprints','screens','levels','components'])fs.mkdirSync(`${root}/${dir}`,{recursive:true});
const style=['art/concepts/c02_core_screens_board.png','art/concepts/c03_five_cats_character_board.png'];
const common=`Use case: ui-mockup. Produce ONE full-bleed high-fidelity portrait game screen, 750×1334 logical coordinates, roughly 9:16, no phone bezel or presentation board. Game: 喵喵回窝. Reference 1 is STYLE ONLY: use its illustrated warm garden, cream paper inset panels, honey wood rims and tactile rounded buttons, NOT its three-panel layout. Reference 2 locks the five cat identities: orange striped round tabby; fluffy white ragdoll with blue eyes and dark points; blue-grey small-eared round cat; orange/white/black calico; purple-black pointed-ear cat with yellow eyes. Keep hand-painted stylized cozy casual-game quality, high-contrast patterns, rounded silhouettes and gentle highlights; no photoreal fur, cheap flat blobs or glossy plastic. Brown text on cream, coral/orange primary, mint secondary, purple video-reward action. Text must be correctly spelled simplified Chinese, legible and CENTERED inside buttons. Top 7% and bottom 6% are safe background only; do not put controls there. Do not make excessive empty sky. No debug metrics, watermarks, unrelated features, rankings, energy systems, cash payments, automatic advertisements or unreadable filler. All numeric values below are illustrative screen state, not final level balancing. `;
const jobs=[];
function job(id,brief,category='screens',references=style){
  const prompt=common+brief;
  jobs.push({id,category,prompt,references,output:`${root}/${category}/${id}.png`,status:'PLANNED'});
  fs.writeFileSync(`${root}/prompts/${id}.prompt.md`,`# ${id}\n\n${prompt}\n\nTool: built-in image_gen.imagegen, no model selector exposed; requested preference gpt-image-2, actual backend not verified.\n`);
}
job('p01_home','Reference3 is the HARD LAYOUT BLUEPRINT, not a style reference. Keep the currency pill, settings control, title, five-cat hero area, primary button and three navigation cards at exactly its locations and relative sizes. Replace its colored rectangles and placeholder words with finished illustrated game UI. Text to KEEP verbatim: "喵喵回窝", "128", "继续第 1 关", "关卡", "图鉴", "外观". Replace the blueprint fish character with blue fish icon, replace 设置 with gear icon, replace the hero placeholder 五猫与长椅插画 / 庭院背景，周围小花 with the five lovely cats sitting on a garden bench. Render no placeholder instructional text. Title at y250..360, hero y430..850, main button y948..1048, bottom navigation y1120..1240. Currency top108, settings top108. No excessive blank sky, no controls inside top7% or bottom6%. Do not enlarge the cats or title outside their blueprint areas. Orange tabby central, four other cats framing it. All labels centered on their actual button rectangles. No gameplay track on home.', 'screens',[...style,`${root}/blueprints/p01_home.png`]);
job('p00_loading','Loading page: centered exact title "喵喵回窝" near y350, all five friendly cats peeking from a cardboard box at y550..830. One readable cream loading panel at y970 with a paw progress bar filled to 68% and label "正在准备猫猫的小窝…". Small bottom links "隐私说明" and "适龄提示", above the safe area. Do not fabricate a regulatory approval seal. No gameplay controls, no ad.');
job('p00_load_error','Loading-retry page: same garden and centered game logo, worried but unharmed orange cat holding a disconnected yarn end. A single cream panel with title "网络开小差啦", body "检查网络后再试一次". One centered orange button "重试". Small secondary text action "隐私说明". No fake completed progress and no unsupported offline entry promise.');
job('p06_win','Victory result screen, bright sunny garden. A compact composition from y250 to1200: three lovely gold stars, five cats happily arriving in one open cardboard box, centered title "全员回窝！". Cream score panel with "本关得分" and large "12,680", then small rows "最大连锁 ×9" and fish icon "+82". Large centered orange main button "下一关". Smaller mint button "再玩一次". Below these, two subtle equal cream actions with video and share icons: "奖励翻倍", "分享高光". No giant blank area or cut-off buttons; the next-level button must dominate both ad and share options. All labels centered, generous safe margins.');
job('p06_complete_100','Final level victory screen, same sunny cozy garden and five cats celebrating in a cardboard box, three gold stars. Title "百关回窝！". Cream result card: "第 100 关", score "28,600", fish "+250". Large orange button "返回地图", smaller mint "再玩一次", secondary "分享高光". Do not show 下一关 or 第101关. This is existing victory UI final-level variant, no new game mode.');
job('p07_revive_ad','Failure/revive screen for level 6 onward. Cozy canned-food storeroom backdrop, warm light, five puzzled but unharmed cats sitting among tidy cans. One centered cream panel, title "罐头仓库挤满啦". Body "还差 7 只猫猫" and "队伍后退 25%，末端 3 只回窝". A large purple rounded button with a small film/play icon on left and exact CENTERED label "看视频继续". Clear secondary mint button "免费重开", and text action "返回地图". Keep this UI reusable after EVERY failure: absolutely no once-per-run cap, countdown, remaining-revive limit, exhausted state or coercive/automatic video. No fake close button. Top/bottom safe areas reserved, panel content and all button labels mathematically centered.');
job('p07_revive_free','First-five-level failure screen. Warm storeroom with cute puzzled cats, no injury. Cream dialog title "罐头仓库挤满啦", text "再给猫猫一次机会吧" and "队伍后退 25%，末端 3 只回窝". Main orange button "免费帮一次", secondary mint button "重新开始", text action "返回地图". This is the once-free first-five-level variant, show NO video icon, no ad, no payment.');
job('p05_pause','Paused game overlay. Background shows a strongly softened warm garden game in silhouette, with a clearly central round wicker cat nest; do not invent a visible track layout in this blurred backdrop. Warm translucent brown veil. Centered cream wood-rim dialog at x100..650,y310..1100, title "休息一下" and a sleepy orange cat resting on its top rim. Vertically spaced actions: orange "继续游戏", cream "重新开始", cream "设置", small "返回主页". Buttons centered, clearly differentiated weights. No gameplay movement, stars, ads or rewards.');
job('p05_confirm_exit','A small confirmation dialog over a dimmed paused-game background, cream and honey-wood style. Title "要离开这一局吗？", body "本局进度将不会保留". Two equally readable buttons at the same row: mint "继续游戏" on left, cream "确认离开" on right. Small orange cat resting on rim. Do not imply deleting permanent progress, stars or currency.');
job('p03_prepare_first','First-level preparation page. Title "第 1 关", subtitle "五猫迎宾" on wood sign. Five character cats welcoming the player from a garden bench, all visible. Cream objective panel "让全部猫猫回窝". One centered orange main button "开始回窝" in lower half. Small back arrow within safe region. No boosters, inventory, advertisements, difficulty selector or track thumbnail with invented geometry on this FIRST level.');
job('p03_prepare_regular','Regular-level preparation page, chapter "纸箱小巷", centered title "第 11 关". A cream objective card "让全部猫猫回窝" with a small cute boxed cat and two paw marks indicating its two-stage reveal. Three existing booster cards: star-tipped cat wand "逗猫棒" count 3, green catnip "猫薄荷" count 2, rainbow cat "彩虹猫" count 1. A selection rim on catnip, not a purchase. Main orange button "开始回窝" centered below cards. Small optional secondary video action "领取补给" subordinate to start. Show no invented map/track geometry here.');
job('p08_collection','Cat collection page. Top wood title "猫咪图鉴" and counter "5 / 12", back arrow within safe region. Main cream board with exactly 12 equal cards arranged 3 columns × 4 rows, all within safe area. First five are the distinct base cats with labels "橘猫", "布偶", "蓝猫", "三花", "玄猫". A small new dot on fifth only. Remaining seven cards are neat cat silhouettes with a lock and star thresholds "18", "21", "24", "30", "36", "48", "60". No random new match colors or invented currencies, no giant card beyond board, no scrolling controls covering cards. Warm garden background secondary to the card grid.');
job('p08_detail','Collection detail page. Back arrow and wood header "猫咪档案". Large joyful orange tabby portrait on a cream illustration card, orange striped forehead, round face, four small paws. Name "橘猫". Subtitle "贪吃担当". Short exact sentence "先吃饱，再陪你回窝。". Small row "已收编" with paw seal. Primary mint button "返回图鉴". This is collection art, no match-type upgrade, combat power, stars-for-purchase or paywall.');
job('p09_cosmetics','Cosmetic selection page. Wood title "装扮小窝", fish balance "380", back arrow. One central preview of a wicker cat nest with an orange cat and a subtle paw trail on calm grass. Two tabs "猫窝" (selected) and "拖尾". Four cream item cards in 2×2 grid: default wicker basket "使用中"; leaf-lined basket "使用"; pink cushion basket "150" with blue fish icon; golden-rim basket "500" with fish icon and visibly disabled affordance because balance380 is insufficient. Main button area must not introduce real-money purchase. Soft wood, cream, mint selected rim; exact labels centered.');
job('p10_settings','Settings page, calm sunny garden with one centered cream wood-edged panel. Header "设置" with close icon. Three generously spaced rows, icon + text on left and large soft toggle on right: "音乐" on, "音效" on, "震动" off. Below divider, readable text rows "隐私说明" and "返回主页". Small sleepy orange cat atop panel. No fake platform permissions, no account fields, no red badges. All controls within top7%/bottom6% safe margins.');
job('p11_feedback','ONE component state board, landscape is allowed for this asset only. Cream background and consistent warm game panel styles. Four distinct clearly separated toast / feedback examples: informational "网络开小差，进度已保存在本机" with cloud icon; unavailable video "暂时没有视频，先重试这一关吧" with film icon; cancelled video "看完才能领取哦"; success "小鱼干到账啦" with fish icon. Also one compact loading button labeled "视频准备中…" and one ready button "看视频继续". This is a state board, not six separate completed pages. Do not invent a finite revive cap.','components');
job('buttons_states','ONE coherent UI button component-state board, landscape allowed. Cream background with column labels "常态", "按下", "禁用", "加载". Four rows: coral main button "开始回窝", mint secondary "重新开始", purple video button "看视频继续", cream text button "返回地图". Precisely aligned sizes and centered text, pressed states visibly depressed with reduced shadow; disabled desaturated but readable; loading with spinner and readable progress label. Include a lower row of four small circular icon buttons: pause, settings, back, close. No extra page mockups, no cats covering labels.','components');
job('gameplay_components','ONE consistent gameplay component-state board, landscape allowed. Warm cream background, 3 clear rows with generous spacing: (1) five base cat tokens using exact reference identities, each normal and nervous pair, with labels "橘猫", "布偶", "蓝猫", "三花", "玄猫"; (2) three booster buttons star cat-wand "逗猫棒", leaf "猫薄荷", rainbow cat "彩虹猫", each available count3, empty count0, selected state; (3) three purr progress bars labeled "呼噜积蓄", "呼噜满啦", "呼噜暴走", with purple-to-honey fill, paw endpoint and controlled glow. Compact but legible consistent sizes. No random extra booster type.','components');
job('obstacles_launcher','ONE component illustration board, landscape allowed. Warm cream background, neatly spaced columns of established game objects: a single compact wooden source doorway with teal paw sign and one opening; a distinct single-opening canned-food lair marked with a fish/can emblem in normal, warning, and full-of-cats states; central circular wicker launcher with orange current cat and a SMALL adjacent next-cat pocket in ready, empty, swapping states. Lower row: paper-box cat with two marks, one mark, and open box; dusty cat obscured and revealed. Exactly one mouth per source/lair drawing, launcher visually unlike a track entrance, no two-story doors, no weapons, no harm. Label groups "迷路入口", "罐头老巢", "引路猫窝", "纸箱猫", "灰扑扑猫".','components');
const themes=['晴日庭院：暖阳、青绿草地、小野花、远处木栅栏','纸箱小巷：温暖石板、整齐纸箱、小巷盆栽','灰尘花房：温室玻璃、柔光、盆栽、淡绿地面','弯桥午后：浅水庭院、午后光、边缘小桥，仅装饰不得形成第二轨道','海风猫站：浅蓝海风、木质站台、边缘缆绳与贝壳','果园仓库：暖金果园、边缘木箱和树叶','雪夜长廊：温暖灯光、蓝白薄雪边缘，轨道不积雪','星光屋顶：靛蓝屋顶远景、柔和星光、暖色轨道','灯会巡游：边缘小灯笼、暖红金光，轨道区安静','百猫回窝：金色庭院庆典、边缘小彩旗，仍是清晰猫咪游戏'];
for(let chapter=1;chapter<=10;chapter++){
  const start=(chapter-1)*10+1;
  job(`p02_map_${String(chapter).padStart(2,'0')}`,`Chapter map screen for "${catalog.chapters[chapter-1]}". Scene: ${themes[chapter-1]}. Header "关卡地图" and small chapter title. Show exactly ten numbered pawprint stepping-stone level nodes, in a readable winding vertical MAP trail, numbers ${Array.from({length:10},(_,i)=>start+i).join(', ')} in this exact ascending order from top to bottom. This is a map navigation path, not a playable Zuma track; no launcher. First three nodes completed with small gold stars, fourth highlighted as current, remaining six muted with locks. All numbers must be correct and visible, no duplicated or missing nodes. Current node stays around screen middle. Back arrow at top safe region, small bottom chapter arrow controls, no energy or ads.`);
}
const palette=['#f9a64c','#fff1df','#8aa7ba','#d19a54','#554654'];
for(const l of catalog.levels){
  const id=String(l.id).padStart(3,'0'),p=parameterize(makePath(l.geometry)),profile=l.geometryProfile;
  const points=resample(p,4),d=points.map((q,i)=>`${i?'L':'M'}${q.x.toFixed(2)} ${q.y.toFixed(2)}`).join(' ');
  const cats=makeCats(p,.70,profile.spacing,profile.catRadius);
  const arrows=[];for(let s=60;s<p.length-60;s+=200){const q=at(p,s),b=at(p,s+5);arrows.push(`<path d="M-10,-7 L10,0 L-10,7" fill="none" stroke="#334155" stroke-width="3" transform="translate(${q.x} ${q.y}) rotate(${Math.atan2(b.y-q.y,b.x-q.x)*180/Math.PI})"/>`);}
  const mouth=(q,kind)=>`<g transform="translate(${q.x} ${q.y}) rotate(${q.angle*180/Math.PI})"><path d="M0,-40 H${kind==='S'?-40:40} V40 H0" fill="#fff" stroke="${kind==='S'?'#087f6d':'#ae3544'}" stroke-width="6"/></g>`;
  const mark=(q,kind)=>`<text x="${q.x}" y="${q.y-49}" text-anchor="middle" font-size="20" fill="${kind==='S'?'#087f6d':'#ae3544'}">${kind}</text>`;
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="750" height="1334"><rect width="750" height="1334" fill="#faf8ef"/><g font-family="sans-serif"><rect x="30" y="92" width="88" height="88" rx="22" fill="#e5dfd2"/><text x="74" y="145" text-anchor="middle" font-size="26">Ⅱ</text><text x="375" y="130" text-anchor="middle" font-size="32">第 ${l.id} 关</text><rect x="560" y="98" width="140" height="55" rx="25" fill="#e5dfd2"/><text x="630" y="135" text-anchor="middle" font-size="24">鱼 128</text><rect x="170" y="153" width="380" height="27" rx="13" fill="#d1c5e5"/><text x="360" y="174" text-anchor="middle" font-size="18">呼噜 68%</text><path d="${d}" fill="none" stroke="#a5afbe" stroke-width="${profile.trackWidth}" stroke-linecap="butt"/><path d="${d}" fill="none" stroke="#e9ecf0" stroke-width="${profile.trackWidth-6}"/>${arrows.join('')}${mouth(l.source,'S')}${mouth(l.lair,'L')}${mark(l.source,'S')}${mark(l.lair,'L')}${cats.map(c=>`<circle cx="${c.x}" cy="${c.y}" r="${profile.catRadius}" fill="${palette[c.color]}" stroke="#53463c" stroke-width="2"/><text x="${c.x}" y="${c.y+6}" text-anchor="middle" font-size="18">${['橘','偶','蓝','花','玄'][c.color]}</text>`).join('')}<circle cx="375" cy="675" r="62" fill="#d9b67f" stroke="#705a40" stroke-width="5"/><text x="375" y="685" text-anchor="middle" font-size="26">中央</text><circle cx="411" cy="705" r="20" fill="#8aa7ba"/><text x="411" y="711" text-anchor="middle" font-size="16">次</text>${[166,375,584].map((x,i)=>`<rect x="${x-48}" y="1168" width="96" height="88" rx="20" fill="${['#af97cc','#9ec9ad','#e6b981'][i]}"/><text x="${x}" y="1218" text-anchor="middle" font-size="23">${['棒','草','虹'][i]}</text>`).join('')}</g></svg>`;
  fs.writeFileSync(`${root}/blueprints/l${id}.svg`,svg);
  job(`l${id}`,`GAMEPLAY SCREEN, level ${l.id}, theme: ${themes[l.chapter-1]}. Reference 3 is the HARD GEOMETRY BLUEPRINT at 750×1334: replace its schematic strokes with beautiful warm cream/honey-wood track, circles with the five recognizable cat tokens, and grey widgets with finished UI. Do NOT redesign or simplify the path. It has ONE source at (${l.source.x.toFixed(1)},${l.source.y.toFixed(1)}) with forward tangent ${(l.source.angle*180/Math.PI).toFixed(1)} degrees; ONE lair at (${l.lair.x.toFixed(1)},${l.lair.y.toFixed(1)}) with terminal tangent ${(l.lair.angle*180/Math.PI).toFixed(1)} degrees; ONE launcher exactly at (375,675), not at bottom. Degrees are screen coordinates: 0 right,90 down. Source uses teal paw doorway, lair a DIFFERENT single-opening canned-food shed, each flush with exactly its matching endpoint, never connected elsewhere. The track must stay one continuous OPEN curve with no extra loop, branch, shortcut, gap, crossing, bridge, unused dead-end or decorative path resembling a second track. Preserve every bend, track centerline, both endpoint orientations, scale and central launcher's position from reference3. Track width ${profile.trackWidth}px, cat body diameter ${profile.catRadius*2}px, neighboring centers follow path at ${profile.spacing}px intervals; all cats centered ON the rail, not beside it. Tokens depict the five established cat varieties, no letter labels on cats. Cats face the viewer, footprints follow the blueprint arrows. A wicker circular central launcher with current orange cat and a small next-blue-cat preview pocket centered at (411,705), radius 20px, without extending into the track. No floor artwork may obscure cat silhouettes. Top HUD: pause at left, exact centered text "第 ${l.id} 关", fish icon "128" on right, purr bar below titled "呼噜". Bottom exactly three compact controls: star-tipped cat wand, catnip leaf, rainbow cat, each count "3", inside y1168..1256; no fourth tool. Remove blueprint letters S,L,中央,次 and technical labels; topology must remain visibly understandable through distinct single-mouth objects and subtle directional pawprints. Quiet negative space in launcher area, theme decoration only outside rails. Illustrate a regular mid-game state, not imminent failure or victory. Geometry hash ${l.sourceSha256}.`, 'levels',[...style,`${root}/blueprints/l${id}.png`]);
}
fs.writeFileSync(`${root}/jobs.json`,JSON.stringify({phase:'IMAGEGEN_ONLY',date:'2026-09-08',model:'BUILTIN_BACKEND_UNEXPOSED',total:jobs.length,jobs},null,2)+'\n');
console.log(`Prepared ${jobs.length} image briefs; none is marked generated by this script.`);
