async (page) => {
  const errors=[];const handler=m=>{if(['warning','error'].includes(m.type()))errors.push({type:m.type(),text:m.text()});};page.on('console',handler);
  await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>window.__UI_FLOW__?.page==='home');
  const read=()=>page.evaluate(()=>window.__UI_FLOW__);
  const frame=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const assert=(v,m)=>{if(!v)throw Error(m);};
  const click=async(name)=>{const s=await read(),c=s.controls.find(c=>c.name===name);assert(c,'Missing '+name+' in '+s.page+'/'+s.panel);const box=await page.locator('#GameCanvas').boundingBox();let x=c.rect.x+c.rect.width/2,y=c.rect.y+c.rect.height/2;if(c.space==='stage'){x=s.fit.x+x*s.fit.scale;y=s.fit.y+y*s.fit.scale;}await page.mouse.click(box.x+x/s.viewport.width*box.width,box.y+y/s.viewport.height*box.height);await frame();};
  const settled=async()=>{await page.waitForFunction(()=>!window.__UI_FLOW__.pending);await frame();};
  const shot=async(name)=>page.locator('#GameCanvas').screenshot({path:'output/playwright/ui06/'+name+'.png'});
  const scenario=async(i)=>{await click('debug-states');await click('case'+i);};
  const touches=async()=>{const s=await read(),cs=s.controls.filter(c=>c.space==='stage');for(const c of cs){assert(c.rect.width*s.cssScale*s.fit.scale>=43.99&&c.rect.height*s.cssScale*s.fit.scale>=43.99,'small '+c.name);assert(c.rect.x>=0&&c.rect.y>=0&&c.rect.x+c.rect.width<=750&&c.rect.y+c.rect.height<=1334,'outside '+c.name);}for(let i=0;i<cs.length;i++)for(let j=i+1;j<cs.length;j++){const a=cs[i].rect,b=cs[j].rect;assert(!(a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y),'overlap '+cs[i].name+'/'+cs[j].name);}};
  await shot('home');await click('entry0');assert((await read()).page==='map'&&(await read()).chapter===2,'map locates current');await click('chapterPrev');await click('chapterPrev');
  const chapters=[];for(let i=0;i<10;i++){const s=await read(),levels=s.controls.filter(c=>/^level\d/.test(c.name));assert(levels.length===10,'map count');chapters.push(levels.map(c=>c.name));await touches();if(i<9)await click('chapterNext');}assert(chapters.flat().length===100,'100 entries');await shot('chapter10-locked');await click('level100');assert((await read()).page==='map','locked level opened');await click('mapHome');
  await click('start');assert((await read()).page==='prepare'&&(await read()).selectedLevel===24,'home current');await shot('prepare24');await click('prepareTool1');await click('toolBack');await click('beginLevel');await settled();assert((await read()).page==='game','launch sample');
  await click('tool1');assert((await read()).controls.find(c=>c.name==='useTool').state==='disabled','empty tool');await shot('empty-tool');await click('toolBack');
  await click('pause');await click('settings');const before=(await read()).settings.music;await click('setting-music');await settled();assert((await read()).settings.music!==before,'setting change');await click('privacy');await shot('privacy');await click('privacyBack');await click('settingsBack');assert((await read()).panel==='pause','settings caller');await click('continue');
  await click('debug-home');await click('entry1');await shot('collection-new');await click('card0');await shot('card-detail');await click('detailBack');assert((await read()).viewed.includes(0),'viewed');await click('cardsNext');await shot('collection-locked');await click('card11');assert((await read()).panel==='','locked card opened');await click('cardsHome');
  await click('entry2');await shot('cosmetics');await click('cosmetic-nest1');await click('buy');await settled();assert((await read()).fish===30&&(await read()).owned.includes('nest1'),'purchase');await click('cosmetic-nest1');assert((await read()).equipped.nest==='nest1','equip');await click('trailTab');await click('cosmetic-trail2');assert((await read()).fish===30&&(await read()).panel==='','insufficient');await shot('cosmetics-insufficient');
  await scenario(1);await click('debug-home');await click('homeSettings');const old=(await read()).settings.sound;await click('setting-sound');await settled();assert((await read()).panel==='saveError'&&(await read()).settings.sound===old,'failed setting changed');await shot('save-error');await click('saveBack');await click('settingsBack');
  await click('debug-boot');await settled();assert((await read()).panel==='loadError','boot failure');await shot('boot-error');await click('loadCancel');await scenario(0);
  await click('start');await click('beginLevel');await click('cancelPrepare');await settled();assert((await read()).page==='home','late load navigated');
  await click('start');await click('beginLevel');await settled();await click('debug-lose');await click('revive');await click('freeMap');await settled();assert((await read()).page==='map'&&(await read()).resumes===0,'late revive navigated');
  await scenario(2);await click('debug-lose');await click('revive');await settled();assert((await read()).panel==='error'&&(await read()).resumes===0,'cancel revived');await shot('revive-cancel');await scenario(0);await click('debug-lose');await click('revive');await settled();await click('debug-lose');await click('revive');await settled();assert((await read()).resumes===2,'repeated revive');
  await scenario(3);await click('debug-lose');await click('revive');await settled();await click('debug-lose');assert((await read()).controls.find(c=>c.name==='revive').state==='disabled','free cap');await shot('free-used');await click('freeRestart');assert((await read()).resumes===0,'free restart');await shot('first-guide');
  await scenario(4);await click('debug-win');await shot('final-result');await click('next');assert((await read()).page==='map'&&(await read()).chapter===9,'100 goes map');await click('level100');await click('cancelPrepare');assert((await read()).chapter===9,'map position');
  await click('chapterPrev');await click('level87');await click('beginLevel');await settled();assert((await read()).level===87,'87');await click('debug-win');const fish=(await read()).fish;await click('bonus');await click('perform');await settled();assert((await read()).fish===fish+214,'bonus amount');assert((await read()).controls.find(c=>c.name==='bonus').state==='disabled','bonus duplicate');await click('share');await click('perform');await settled();assert((await read()).panel==='win','share return');
  await click('winHome');await click('entry1');await click('cardsNext');await click('card11');await shot('card12');await click('detailBack');
  const sizes=[];
  for(const [width,height] of [[360,640],[390,844],[430,932]]){
    await page.setViewportSize({width,height});await page.reload();await page.waitForFunction(()=>window.__UI_FLOW__?.page==='home');await click('debug-safe');
    await touches();await click('entry0');await touches();await shot('map-safe-'+width);await click('mapHome');await click('entry1');await touches();await click('card0');await touches();await click('detailBack');await click('cardsHome');await click('entry2');await touches();await click('cosmetic-nest1');await touches();await click('buyCancel');await click('backHome');await click('homeSettings');await touches();await click('privacy');await touches();await click('privacyBack');await click('settingsBack');await click('start');await touches();await click('beginLevel');await settled();await click('pause');await touches();await click('continue');await click('debug-win');await touches();await shot('win-safe-'+width);await click('share');await touches();await click('rewardBack');await click('debug-lose');await touches();await shot('revive-safe-'+width);sizes.push({width,height,fit:(await read()).fit});
  }
  page.off('console',handler);assert(!errors.length,'diagnostics '+JSON.stringify(errors));return {passed:true,chapters,sizes,diagnostics:errors,final:await read()};
}
